Redux
AndriyMelnykIt/Search_Image pull request #2
Opened 2021-11-24 11:44 UTC by AndriyMelnykIt

2021-11-26 08:51 UTC, mike-gusiev requested changes

2021-11-26 08:51 UTC, mike-gusiev commented on src/Components/AllComponents.js
> +export { default as HomePage } from './HomePage';
назови цей файл index

2021-11-26 08:51 UTC, mike-gusiev commented on src/Components/Header.jsx
> +			<Container to='/'>
атрибути jsx мають мати подвійні кавички

2021-11-26 08:51 UTC, mike-gusiev commented on src/Components/Pages.jsx
> +export default Pages;
перед відправкою пул реквеста на рев'ю переглядай свій пул реквест. і виправиш все що помітиш самостійно, до того як мені відправляти на рев'ю.

якщо бачиш таку іконку, значить у цього файлу не вистачає переносу рядка в кінці.

2021-11-26 08:51 UTC, mike-gusiev commented on src/Components/SearchHistory.jsx
> +	return (
використовуй коротку форму es6 функцій без return, там де це можливо

2021-11-26 08:51 UTC, mike-gusiev commented on src/Components/SearchPage.jsx
> +		return;
а нашо цей return?

2021-11-26 08:51 UTC, mike-gusiev commented on src/api.js
> +
зайві перенос рядків

2021-11-26 08:51 UTC, mike-gusiev commented on src/App.js
> +		<BrowserRouter>
поміняй відступи на 4 пробіла замість табів. таби більше ніхто не використовує

2021-11-26 08:51 UTC, mike-gusiev commented on src/redux/ducks/ducksGeneration.js
> +import axios from '../../api';
перейменуй цей файл. щоб по назву дака було понятно за який модуль він відповідає

2021-11-26 08:51 UTC, mike-gusiev commented on src/redux/ducks/reducer.js
> +import { combineReducers } from 'redux';
позбуться цього файлу. combineReducers помісти в src/redux/store.js

2021-11-29 08:01 UTC, mike-gusiev requested changes

2021-11-29 08:01 UTC, mike-gusiev commented on src/Components/Homepage.jsx
> +	<>
заміни таби на пробіли усюди. зроби щоб твоя IDE показувала де таби а де пробіли

2021-11-29 08:01 UTC, mike-gusiev commented on src/Components/PhotosPage.jsx
> +	return <Photos />;
позбудься цього компоненту. він зайвий

2021-11-29 08:01 UTC, mike-gusiev commented on src/Components/Walty photos/Photos.jsx
> +    return {
використовуй коротку форму es6 функцій

2021-11-29 08:01 UTC, mike-gusiev commented on src/index.js
> +);
перенос рядка

2021-11-29 08:01 UTC, mike-gusiev commented on src/redux/ducks/Walty Photos.js
> +}
перенос рядка

2021-11-29 08:01 UTC, mike-gusiev commented on src/redux/ducks/Walty Photos.js
> +import axios from '../../api';
позбуться пробілів у назві файлів

2021-11-29 08:01 UTC, mike-gusiev commented on src/styled/SearchPage.js
> +;
неправильно відпступи і переноси зроблені

2021-11-29 08:01 UTC, mike-gusiev commented on src/styled/variables.js
> +export const mediaScreen = '(max-width: 1199px) and (min-width: 992px)';
перенос рядка

2021-11-29 10:07 UTC, AndriyMelnykIt commented on src/Components/Homepage.jsx
> +	<>
в мене зараз стоїть 1 Tab = 4 spaces

2021-11-29 11:10 UTC, merged